# Generated by Django 4.1.1 on 2022-09-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='desk',
            new_name='content',
        ),
    ]
